### ISSUE TITLE
Ensure that dependencies are in sync and add smoke tests

### ISSUE THREAD

**Issue by csadorf** [conda-forge/aiida-core-feedstock#48]
This is a follow-up issue to #46 . Currently there is no automated check whether dependencies specified in the recipe are in sync with [those specified in the core package](https://github.com/aiidateam/aiida-core/blob/a490fe07ab5752f04efaac338c1f1a9ef648426a/setup.json#L23). My suggestion would be to

- [ ] Implement a check similar to [here](https://github.com/aiidateam/aiida-core/blob/a490fe07ab5752f04efaac338c1f1a9ef648426a/utils/dependency_management.py#L210) to ensure that requirements are in sync.
- [ ] Add some very basic smoke tests that check whether the conda package is functional, e.g., simply executing `verdi import` would have caught the issue described in #46.

**Comment by ltalirz** [comment]
Regarding the second point - we do have super basic tests which we can expand
https://github.com/conda-forge/aiida-core-feedstock/blob/6788dea8198b82a9b965a32d59bc8670c9604e4f/recipe/meta.yaml#L64-L75

The signals from conda-forge have been a bit mixed - on this or another package I was told that one should not run a test suite on the conda-forge builds. On the other hand, there are simulation codes compiled here on conda-forge that run their >1h test suite. I.e. I guess we need to find some middle ground

**Comment by sphuber** [comment]
I would personally be hesitant with starting to add unit/integration tests here, simply because we forgot a dependency. I agree that we should have a test that makes sure the list of dependencies for the normal distribution and the conda package are in sync, but starting to actually run `verdi` commands to test this indirectly seems like the wrong approach. Sure this time running `verdi import` would have shown the problem, but only `verdi import`. The dependency could have just as well been somewhere else. This would lead us to start adding more and more tests that don't really should be here.

**Comment by csadorf** [comment]
> I would personally be hesitant with starting to add unit/integration tests here, simply because we forgot a dependency. I agree that we should have a test that makes sure the list of dependencies for the normal distribution and the conda package are in sync, but starting to actually run `verdi` commands to test this indirectly seems like the wrong approach. Sure this time running `verdi import` would have shown the problem, but only `verdi import`. The dependency could have just as well been somewhere else. This would lead us to start adding more and more tests that don't really should be here.

I understand the notion not run the full test suite (i.e. unit and integration tests), but it is not clear to me why we would not want to expand our smoke tests a little bit? We're not testing AiiDA here, we are testing whether there are issues with the package build which is a pretty standard thing to do. I don't follow why those tests "don't really should be here"? What is the downside besides having the package build take 1-2 mins longer?

**Comment by sphuber** [comment]
> I understand the notion not run the full test suite (i.e. unit and integration tests), but it is not clear to me why we would not want to expand our smoke tests a little bit? We're not testing AiiDA here, we are testing whether there are issues with the package build which is a pretty standard thing to do. I don't follow why those tests "don't really should be here"? What is the downside besides having the package build take 1-2 mins longer?

Because it will become significantly more complicated. The current smoke tests don't require a full profile to be configured, complete with required database and repository, and RabbitMQ. This will have to be added. And my point remains, where do you stop? Why is testing `verdi import` reasonable? Should we run a workchain? Where do we stop?

**Comment by csadorf** [comment]
I don't consider a test that would require a profile setup or database for that matter a smoke test. I'd say we stop when tests become too involved, i.e., require external services, additional steps, or simply take too long. Testing `verdi import` (no arguments required!) would have caught this particular issue which makes it reasonable IMO.

Tbh, I am not quite sure where this vehement opposition towards expanding these tests comes from and I have no desire to die on this hill. All I'm suggesting is to expand the tested commands just a little bit so that issues like the one that occurred are more likely to be caught. Since there appears to be no interest in this, I am going to close this issue.

**Comment by sphuber** [comment]
There might have been some misunderstanding. I thought you wanted to actually call `verdi import` to import an archive as that is when the bug would have manifested, not just to see the command is reachable and have it print its help message. My "vehement opposition" was to adding tests that actually require setting up profiles and service, but you seem to agree with that, so I think in the end we are on the same page. If you just want to add another endpoint of `verdi` to call to see if its help message prints properly, then that is fine by me. In that case, maybe it would be useful then to actually add a single test that dynamically discovers all end commands and invokes them with `--help` just to see they are all reachable.

**Comment by ltalirz** [comment]
Hey guys - thanks again to Simon for raising the issue (which I certainly recognize as well).
I've added a PR that adds an import that would have caught the missing package https://github.com/conda-forge/aiida-core-feedstock/pull/49 (note: I checked and `verdi import -h` would not have detected it, i.e. we would actually have had to do an import).

Of course this PR is only patchwork, and I agree it would be good to think how to address the problem systematically.
Here are some propositions:

1) As far as the aspect of dependencies is concerned, since a couple of months the automatic PRs include dependency analysis and it actually did flag the aiida-archive package https://github.com/conda-forge/aiida-core-feedstock/pull/45 (my fault for not recognizing it).
One problem is that the aiida-core conda-forge package comes without the pip extras, and thus there is always a list of packages detected to be missing.
We could try to replicate this with subpackages (e.g. aiida-core.rest , aiida-core.xxx). It looks like the dependency analysis includes dependencies from subpackages (e.g. postgresql), so this should resolve that issue and then make missing dependencies easy to spot going forward.

2) One aspect that is then still missing is the analysis on dependency *versions*, which one currently needs to do manually for every release (I typically check ["git blame" of the setup.json](https://github.com/aiidateam/aiida-core/blame/develop/setup.json) ).
We could add a helper function to `utils/dependency_management.py` that prints the entire `requirements` and `outputs` sections (for subpackages). This requires some "hand massaging" (treatment of special cases like dependencies with extras etc.) but the "hand massaging" aspect will change less frequently than the dependency versions themselves.

3) Even if we implement 1) and 2), not running a test suite keeps some remaining uncertainty on issues being overlooked.
Given the fact, as mentioned before, that other codes run very intensive integration tests on conda, I would personally find running the test suite acceptable.
Over the last year, we have been releasing roughly once per month (counting minor releases) but had >300 commits to `develop` (+ a multiple on PRs) - given that we run 4 jobs on every commit on aiida-core, having one CI run per release/platform would be a negligible fraction.

Let me know what you think - perhaps @astamminger also has some suggestions.

**Comment by astamminger** [comment]
I'm not against testing, but isn’t this discussion a bit overkill just because we forgot to add a single dependency once?

**Comment by chrisjsewell** [comment]
With #54 we now run a `pip check` on the installation. I think that is enough to close this?

**Comment by csadorf** [comment]
> With #54 we now run a `pip check` on the installation. I think that is enough to close this?

I guess.
